from PyGlow import PyGlow
from time import sleep
import os
pyglow = PyGlow()
pyglow.all(0)
pyglow.color("green", 255)
sleep(1)
pyglow.color("green", 0)
sleep(1)
pyglow.color("green", 255)
sleep(1)
pyglow.color("green", 0)
sleep(1)
pyglow.color("green", 255)
sleep(1)
pyglow.color("green", 0)
sleep(1)
pyglow.color("green", 255)
sleep(1)
pyglow.color("green", 0)
sleep(1)
pyglow.color("green", 255)
sleep(1)
pyglow.color("green", 0)
sleep(1)
pyglow.color("green", 255)
sleep(1)
pyglow.color("green", 0)
sleep(1)
pyglow.color("green", 255)
sleep(1)
pyglow.color("green", 0)
sleep(1)
pyglow.color("green", 255)
sleep(1)
pyglow.color("green", 0)
sleep(1)
pyglow.color("green", 255)
sleep(1)
pyglow.color("green", 0)
sleep(1)
pyglow.color("green", 255)
sleep(1)
pyglow.color("green", 0)
sleep(1)
pyglow.color("green", 255)
sleep(1)
pyglow.color("green", 0)
sleep(1)
pyglow.color("green", 255)
sleep(1)
pyglow.color("green", 0)
sleep(1)
pyglow.color("green", 255)
sleep(1)
os.system("sudo python /home/pi/pyglow/tempglow.py")
#os.system("sudo python /home/pi/pyglow/weatherpyglow.py")    #Set either of these, depending on which type of pyglow lamp you want to reset to
 
    

